<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="MAIN" Id="{7a50fa0f-28bc-47ec-9a4c-1bc085b48504}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	aData		: ARRAY[0..9] OF LREAL := [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
	fValue		: LREAL;
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[fValue := F_Calc(ADR(aData), 1, 2);
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="23" Count="0" />
      <LineId Id="25" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>